---
- name: "Ensure openssl is installed."
  package:
    name: openssl
    state=latest

- name: "create configuration directory"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
  - "{{ cert_dir }}"

# - name: "Deploy configuration items"
#   template:
#     src: "{{ item }}.j2"
#     dest: "{{ ca_certs_dir }}/{{ item }}"
#     owner: root
#     group: root
#   with_items:
#     - serial
#     - ca.conf


