---
- name: "Check index for CA/subCA (revocation)"
  stat:
    path: "{{ cert_dir }}/index.txt"
  register: index_file

- name: "Install conf for CA/subCA for revocation purpose"
  template:
    src: "ca.conf.j2"
    dest: "{{ cert_dir }}/ca.conf"
    owner: root
    group: root
    mode: 0755
  when:
    - not index_file.stat.exists

- name: "Install empty index for CA/subCA for revocation purpose"
  file:
    path: "{{ cert_dir }}/index.txt"
    owner: root
    group: root
    mode: 0755
    state: touch
  when:
    - not index_file.stat.exists
