---
# Check for CA cert existence (so we don't getnerate a new onw on every run)
- block:
    - debug:
        msg: "Checking {{ cert.name}} certificate"

    - name: "Check certificate expiration date [ Expecting more than a week before setting regeneration var ... ]"
      openssl_certificate_info:
        path: "{{ cert_dir }}/fullchain.pem"
        valid_at:
          point_panic: "{{ pki.common.expiration_threshold.cert }}"
      register: result

    - name: "Validate that certificate is valid in panic threshold"
      assert:
        that:
          - result.valid_at.point_panic
        fail_msg: "Certificate {{ cert.name }} panic threshold !!"
        success_msg: "Certificate {{ cert.name }} still valid."

    - name: "Check certificate revocation."
      assert:
        that:
          - result.serial_number not in cert.revocations
        fail_msg: "Certificate {{ cert.name }} is REVOKED!!"
        success_msg: "Certificate {{ cert.name }} is not revocked."
      when: cert.revocations is defined

    - name: "force renew certificate"
      assert:
        that:
          - cert.force_renew|default(false) == false
        fail_msg: "Certificate {{ cert.name }} force renew!!"
        success_msg: "Certificate {{ cert.name }} no force renew."

    - name: "Validate Parent CA"
      assert:
        that:
          - result.authority_key_identifier == ca_info.subject_key_identifier
      when: pki.ca is defined

    - debug:
        msg: "{{ cert.name }} is still valid no need to generate"
      
  rescue:
    - name: "Remove CSR and cert files: renew"
      file:
        path: "{{ cert_dir }}/{{ item }}"
        state: absent
      with_items:
        - "priv.csr"
        - "fullchain.pem"
      ignore_errors: true

- name: "Remove cert key files: renew key"
  file:
    path: "{{ cert_dir }}/privkey.pem"
    state: absent
  when: cert.force_renew_key|default(false)
  ignore_errors: true
