---
- name: "Generate ECC privkey {{ cert.name}}."
  openssl_privatekey:
    path: "{{ cert_dir}}/privkey.pem"
    curve: "{{ cert.ECC.curve | default(pki.common.ECC_curve) }}"
    type: ECC
    group: certs
    mode: u=rw,g=r,o=
    passphrase: "{{ certpass }}"
    cipher: "auto"
  when: cert.ECC is defined

- name: "Generate RSA privkey {{ cert.name}}."
  openssl_privatekey:
    path: "{{ cert_dir}}/privkey.pem"
    size: "{{ cert.RSA.bits | default(pki.common.RSA_bits) }}"
    type: RSA
    group: certs
    mode: u=rw,g=r,o=
    passphrase: "{{ certpass }}"
    cipher: "auto"
  when: cert.RSA is defined

