---
# tasks file for ansible-role-ca
- include_vars: "{{ ansible_os_family }}.yml"

- include: pki-init.yml

- include: gen_certs.yml

#- include: distribute_keys.yml
#  when: ca_distribute_keys is defined

