---
# tasks file for ansible-role-ca
- include_vars: "{{ ansible_os_family }}.yml"

- include: pki-init.yml

- name: "Generate certificates."
  include: gen-certs.yml

- name: "Generate CRLs."
  include_tasks: gen-crl.yml
  with_items: "{{ cas_CRL|default([]) }}"

#- include: distribute_keys.yml
#  when: ca_distribute_keys is defined

